apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-mail-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-mail-sender
  template:
    metadata:
      labels:
        app: password-mail-sender
    spec:
      containers:
      - name: password-mail-sender
        env:
          - name: DATA_FOLDER
            value: /data
          - name: JAVA_OPTS
            value: -Dspring.profiles.active=compose
        image: ${DOCKER_REPO}/poc-password-mail-sender
        ports:
          - containerPort: 8080
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: password-mail-sender-claim0
      restartPolicy: Always
      volumes:
        - name: password-mail-sender-claim0
          persistentVolumeClaim:
            claimName: password-mail-sender-claim0