apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-generator
  template:
    metadata:
      labels:
        app: password-generator
    spec:
      containers:
      - name: password-generator
        env:
          - name: DATA_FOLDER
            value: /data/password-generator
          - name: JAVA_OPTS
            value: -Dspring.profiles.active=compose
        image: ${DOCKER_REPO}/poc-password-generator
        ports:
          - containerPort: 8080
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: password-generator-claim0
      restartPolicy: Always
      volumes:
        - name: password-generator-claim0
          persistentVolumeClaim:
            claimName: password-generator-claim0